### ISSUE TITLE
In README.md did you mean 16.04?

### ISSUE THREAD

**Issue by ygale** [sgraf812/ghc-dlas#1]
Thanks for sharing this!

In the `README.md`:

> Provides binary Ubuntu 14.04 LTS tarballs...

BashForWindows is on Xenial by default, isn't that what you built it for?

**Comment by sgraf812** [comment]
Oh, that's weird. My desktop (with which I compiled) happens to have a 14.04 distribution, wheras my recently set up laptop has 16.04 on it.

Anyway, I doubt that it makes a difference, or does it?

**Comment by ygale** [comment]
Come to think of it, now I recall reading somewhere that Microsoft upgraded Ubuntu at some point. It only took effect for new installations of BashForWindows.

In principle it does make a difference, because it changes the versions of dependent libraries and thus also changes the set of Linuxes where this bindist will work. Specifically for 14.04 and 16.04 I haven't seen any compatibility issues. But perhaps it will affect how far into future Ubuntu releases this bindist will work.
